FROM golang:alpine


RUN apk update && apk add --no-cache git

WORKDIR /app

COPY . .

# Copy .env file
COPY .env.example .env

ARG POSTGRES_USER
ENV POSTGRES_USER=${POSTGRES_USER}
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ARG POSTGRES_HOST
ENV POSTGRES_HOST=${POSTGRES_HOST}
ARG POSTGRES_PORT
ENV POSTGRES_PORT=${POSTGRES_PORT}
ARG POSTGRES_DBNAME
ENV POSTGRES_DBNAME=${POSTGRES_DBNAME}

RUN go mod tidy

RUN go build -o binary

ENTRYPOINT ["/app/binary"]